<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-06OKJ4FN" name="firstPackage.DataProviderConcepts" tests="1" failures="0" timestamp="05 Dec 2019 06:18:06 GMT" time="0.000" errors="1">
  <testcase name="crdential" time="0.000" classname="firstPackage.DataProviderConcepts">
    <error type="org.testng.TestNGException" message="
Method private void firstPackage.DataProviderConcepts.crdential(java.lang.String,java.lang.String) requires a @DataProvider named : Credential Data.">
      <![CDATA[org.testng.TestNGException: 
Method private void firstPackage.DataProviderConcepts.crdential(java.lang.String,java.lang.String) requires a @DataProvider named : Credential Data.
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:440)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:601)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1316)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1044)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1134)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- crdential -->
</testsuite> <!-- firstPackage.DataProviderConcepts -->
